<?php

namespace Modules\Discount\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Discount\Models\Discount;

class DiscountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $discounts = [
            [
                'code' => 'FIRST20',
                'name' => ['ar' => 'خصم أول طلب', 'en' => 'First Order Discount'],
                'description' => ['ar' => 'خصم 20% لأول طلب بحد أقصى 30 ريال', 'en' => '20% off first order up to 30 SAR'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_FIRST_ORDER,
                'is_automatic' => false,
                'priority' => 300,
                'value' => 20.00,
                'min_order_amount' => 50.00,
                'max_discount_amount' => 30.00,
                'first_order_only' => true,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'BIG15',
                'name' => ['ar' => 'خصم الطلبات الكبيرة', 'en' => 'Large Order Discount'],
                'description' => ['ar' => 'خصم 15% للطلبات من 150 ريال فأكثر بحد أقصى 40 ريال', 'en' => '15% off orders from 150 SAR up to 40 SAR'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_ORDER_TOTAL_THRESHOLD,
                'is_automatic' => true,
                'priority' => 180,
                'value' => 15.00,
                'min_order_amount' => 150.00,
                'max_discount_amount' => 40.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'PIECES10',
                'name' => ['ar' => 'خصم كثرة القطع', 'en' => 'Pieces Volume Discount'],
                'description' => ['ar' => 'خصم 10% عند طلب 10 قطع أو أكثر', 'en' => '10% off when ordering 10 pieces or more'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_QUANTITY_THRESHOLD,
                'is_automatic' => true,
                'priority' => 170,
                'value' => 10.00,
                'min_items_count' => 10,
                'max_discount_amount' => 35.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'SERVICE25',
                'name' => ['ar' => 'خصم خدمة محددة', 'en' => 'Service Scope Discount'],
                'description' => ['ar' => 'خصم 25% على الخدمة المحددة فقط', 'en' => '25% off a specific service only'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_SERVICE_SCOPE,
                'is_automatic' => true,
                'priority' => 190,
                'value' => 25.00,
                'usage_condition' => Discount::USAGE_CONDITION_SERVICES,
                'usage_service_ids' => [1],
                'application_scope' => Discount::APPLICATION_SCOPE_SERVICES,
                'discount_service_ids' => [1],
                'max_discount_amount' => 25.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'DELIVERY50',
                'name' => ['ar' => 'خصم على التوصيل', 'en' => 'Delivery Discount'],
                'description' => ['ar' => 'خصم 50% على رسوم التوصيل', 'en' => '50% off delivery fee'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_DELIVERY_FREE,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_DELIVERY_DISCOUNT,
                'is_automatic' => true,
                'priority' => 220,
                'value' => 50.00,
                'applies_to_delivery' => true,
                'delivery_discount_type' => 'percentage',
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'LOYAL10',
                'name' => ['ar' => 'خصم العملاء المتكررين', 'en' => 'Repeat Order Discount'],
                'description' => ['ar' => 'خصم 10% بعد 3 طلبات مكتملة', 'en' => '10% off after 3 completed orders'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_REPEAT_ORDER,
                'is_automatic' => true,
                'priority' => 160,
                'value' => 10.00,
                'min_repeat_orders' => 3,
                'max_discount_amount' => 25.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'WEEKEND15',
                'name' => ['ar' => 'خصم نهاية الأسبوع', 'en' => 'Weekend Discount'],
                'description' => ['ar' => 'خصم 15% أيام الخميس والجمعة', 'en' => '15% off on Thursday and Friday'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_TIME_WINDOW,
                'is_automatic' => true,
                'priority' => 150,
                'value' => 15.00,
                'active_days_of_week' => [4, 5],
                'max_discount_amount' => 30.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'VIP20',
                'name' => ['ar' => 'خصم العملاء المميزين', 'en' => 'VIP Discount'],
                'description' => ['ar' => 'خصم 20% لعملاء VIP بحد أقصى 35 ريال', 'en' => '20% off for VIP clients up to 35 SAR'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_CUSTOMER_SEGMENT,
                'is_automatic' => true,
                'priority' => 210,
                'value' => 20.00,
                'segment_filters' => [
                    'vip_only' => true,
                    'vip_min_orders' => 5,
                ],
                'max_discount_amount' => 35.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'BUNDLE30',
                'name' => ['ar' => 'خصم الباقة', 'en' => 'Bundle Discount'],
                'description' => ['ar' => 'خصم 30% عند اختيار باقة الخدمات المحددة', 'en' => '30% off for the configured service bundle'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_BUNDLE,
                'is_automatic' => true,
                'priority' => 200,
                'value' => 30.00,
                'bundle_rules' => [
                    [
                        'service_ids' => [1, 2],
                        'min_quantity' => 2,
                    ],
                ],
                'max_discount_amount' => 45.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'VENDOR15',
                'name' => ['ar' => 'خصم ممول من المغسلة', 'en' => 'Vendor Funded Discount'],
                'description' => ['ar' => 'خصم 15% ممول من المغسلة', 'en' => '15% vendor-funded promotion'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_ORDER,
                'promotion_kind' => Discount::KIND_VENDOR_FUNDED,
                'is_automatic' => true,
                'priority' => 140,
                'funding_source' => 'vendor',
                'value' => 15.00,
                'max_discount_amount' => 30.00,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
            [
                'code' => 'WALLET10',
                'name' => ['ar' => 'بونص شحن المحفظة', 'en' => 'Wallet Top-up Bonus'],
                'description' => ['ar' => 'اشحن 100 ريال وخذ 10% بونص', 'en' => 'Top up 100 SAR and get 10% bonus'],
                'type' => Discount::TYPE_PERCENTAGE,
                'discount_type' => Discount::DISCOUNT_TYPE_GLOBAL,
                'promotion_domain' => Discount::DOMAIN_WALLET_TOPUP,
                'promotion_kind' => Discount::KIND_WALLET_TOPUP_BONUS,
                'is_automatic' => true,
                'priority' => 250,
                'value' => 10.00,
                'min_wallet_topup_amount' => 100.00,
                'wallet_bonus_percent' => 10.00,
                'wallet_bonus_amount' => null,
                'is_active' => true,
                'start_date' => now(),
                'end_date' => now()->addMonths(6),
            ],
        ];

        foreach ($discounts as $discount) {
            Discount::updateOrCreate(
                ['code' => $discount['code']],
                $discount
            );
        }
    }
}
